#ifndef LOAD_BALANCING_SIMULATION_REQUEST_H
#define LOAD_BALANCING_SIMULATION_REQUEST_H
extern long reqIdGen;

class Request {
    int timestamp;
    long forwardingTimestamp;
    double finishedTimestamp;
    int reqSize;
    int respSize; // bytes
    int pendingSize;
    int sentBy; // server number; -1 for dispatcher
    long reqId;  // autogenerated incrementing

public:
    static double generate_random_number(double low, double high);

    Request(int timestamp, int reqSize, int sentBy);

    long getReqId();

    int getRespSize();

    int getPendingSize();

    int getTimestamp();

    void updatePendingSize(int bytesProcessed);

    int getSentBy();

    void updateSentBy(int resentBy);

    long getForwardingTimestamp();

    void updateForwardingTimestamp(long forwardingTimestamp);

    double getFinishedTimestamp();

    void updateFinishedTimestamp(double finishedTimestamp);
};

#endif //LOAD_BALANCING_SIMULATION_REQUEST_H
